### ISSUE TITLE
Disable exchange pair with no volume

### ISSUE THREAD

**Issue by Emzy** [bisq-network/bisq-pricenode#10]
We had a few times the problem that trading was halted on an exchange.
But we still used the price from that exchange pair to aggregate an average. 
This ends in a wrong average exchange rate.

The pricenode needs to automatically stop using exchange rates that has no volume.

Poloniex right now:
<img width="1728" alt="Screen Shot 2022-08-01 at 21 06 28" src="https://user-images.githubusercontent.com/1223908/182227522-1ea7379f-9bcb-49b4-821a-d9c5136fd0e2.png">

**Comment by ghost** [comment]
The screenshot above from when the problem was happening shows a positive volume, so in this case the exchange rate would still be counted.

Do you have any suggestions on how to resolve this issue?

**Comment by jmacxx** [comment]
The screenshot above from when the problem was happening shows a positive volume, so in this case the exchange rate would still be counted.

Do you have any suggestions on how to resolve this issue?

**Comment by Emzy** [comment]
It shows a volume of "0".
The volume or the timestamp of the last trade are the first things I can think of.
Alternatively an exchange rate that is off by more than ~2% or so could be automatically excepted.

**Comment by ghost** [comment]
> We had a few times the problem that trading was halted on an exchange.
> But we still used the price from that exchange pair to aggregate an average.
> This ends in a wrong average exchange rate.

This bug was fixed by [PR #19,](https://github.com/bisq-network/bisq-pricenode/pull/19) can be closed.
