### ISSUE TITLE
Abnormal Exchange rate provider price impacting Bisq Market Rates

### ISSUE THREAD

**Issue by dutu** [bisq-network/bisq-pricenode#47]
The price of XMR on Poloniex has been unusually low for the past few weeks, 2-4% lower than the average market price. This deviation is due to Poloniex's suspension of XMR deposits and withdrawals, preventing arbitrage and causing their price to diverge from the market average. This discrepancy is affecting the accuracy of the Bisq market price.

Suggested Solution:
To address this, Poloniex should be excluded from the price calculation. Considering the involvement of multiple price nodes, manually adjusting each node's configuration to exclude or include specific exchanges may not be practical. Instead, implementing a mechanism to assess and automatically exclude exchange rate providers whose prices deviate significantly from a predetermined range could be more effective solution.

**Comment by ghost** [comment]
Poloniex XMR price is automatically removed at the source when it deviates too much, e.g:

`POLO XMR outlier price removed:0.00295, lower/upper bounds:0.0030139/0.003039, consensus price:0.0030259666666666665`
